### ISSUE TITLE
Why (0,3,2,1) for transpose and not (0,2,3,1)?

### ISSUE THREAD

**Issue by brando90** [mttk/STL10#2]
I was looking at https://github.com/mttk/STL10/blob/master/stl10_input.py#L60:

```
images = np.transpose(images, (0, 3, 2, 1))
```

is there a reason that you have ` (0, 3, 2, 1)` and not something else?

I noticed that if you change it to `(0, 2, 3, 1)` the images get flipped. Does it mean that the first 96 that appears from `images = np.reshape(everything, (-1, 3, 96, 96)) ` corresponds to the HEIGHT but the second 96 corresponds to WIDTH? When you transpose it since the 3 goes before the 2 in `(0, 3, 2, 1)` it made me assume that since the 2 stayed in the same position that it was the height pixel index.

**Comment by mttk** [comment]
That's due to the format of STL-10 - each image is stored as column-major order flattened matrices for each channel in sequence, meaning that - as you assumed in your comment, the first 96 corresponds to H, while the second 96 corresponds to W. 

Since matplotlib assumes that the image is in HxWx[RGB] format, we have to re-shuffle the data (which is originally stored as a sequence of [RGB]xWxH matrices). The reshuffling order is strictly for display purposes.
